# KIS API 설정
kis:
  api:
    base-url: ${KIS_BASE_URL:https://openapivts.koreainvestment.com:29443}
    app-key: ${KIS_SANDBOX_APP_KEY:PSLNzXOT3Kq7PSV2DPUgWe1lQPRz1plfTIww}
    app-secret: ${KIS_SANDBOX_APP_SECRET:U0ssP79tV6UOHrPyhA3jaPOaiDYY1dClnFUw0R9nettLAgqZov11ZB1/UZ+jMAVliF1yTiJlzUAW7VzT2+U9bjcyiHv8lbiK/fLI8psEm8ZY7RoTuPSMWb4/RhyO2nGO07LacmRaOq9W0asWIJ+nysZtzZq7C+pgqkH0rUklHEYDCPpFPAU=}
    account-no: ${KIS_SANDBOX_ACCOUNT_NO:50138942}
    environment: sandbox

  # 토큰 관리 설정
  token:
    cache-duration-hours: 6      # KIS 정책: 6시간 갱신 주기
    expiry-duration-hours: 24    # KIS 정책: 24시간 유효기간
    safety-margin-minutes: 5     # 만료 5분 전 갱신
