# Test Profile Configuration - H2 In-Memory Database for Testing
spring:
  config:
    activate:
      on-profile: test
      
  # H2 In-Memory Database for Testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always

# Test Logging Configuration
logging:
  level:
    org.springframework.web: INFO
    com.quantum: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.test: DEBUG

# Test에서는 Kafka, Redis 등 외부 의존성 비활성화 또는 Mock 사용
# (필요시 TestContainers 또는 Embedded 버전 사용)

# Trading Configuration - Even in test environment, disable simulation modes
trading:
  execution:
    enabled: false  # Disabled in test environment
    simulate: false  # DISABLED: No simulation even in tests
  data:
    mock-enabled: false  # DISABLED: Force real data sources even in tests