server:
  port: 8080

spring:
  profiles:
    active: development

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

# Axon Framework Configuration
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson

# API Documentation
springdoc:
  api-docs:
    enabled: true
    path: /docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Logging Configuration
logging:
  level:
    com.quantum.web: DEBUG
    com.quantum.trading.platform: DEBUG
    org.springframework.web: INFO
    org.axonframework: INFO

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# CORS Configuration
cors:
  allowed-origins:
    - "http://localhost:3000"  # Next.js 개발 서버
    - "http://localhost:3001"  # React 개발 서버
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true



---
# Development Profile
spring:
  config:
    activate:
      on-profile: development
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    com.quantum: TRACE

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
logging:
  level:
    root: WARN
    com.quantum: INFO
