services:
  postgres:
    image: postgres:15
    container_name: quantum-postgres
    environment:
      POSTGRES_DB: quantum_trading
      POSTGRES_USER: quantum
      POSTGRES_PASSWORD: quantum123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: