services:
  # Axon Server - Event Store & Message Hub
  axon-server:
    image: axoniq/axonserver:2023.2.0
    hostname: axon-server
    container_name: quantum-axon-server
    ports:
      - "8024:8024"  # HTTP API & UI
      - "8124:8124"  # gRPC
    environment:
      - AXONIQ_AXONSERVER_STANDALONE=true
      - AXONIQ_AXONSERVER_HOSTNAME=axon-server
      - AXONIQ_AXONSERVER_DOMAIN=quantum-trading
    volumes:
      - axon-data:/data
      - axon-events:/eventdata
      - axon-config:/config
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8024/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL - Query Side Database
  postgres:
    image: postgres:15-alpine
    container_name: quantum-postgres
    environment:
      POSTGRES_DB: quantum_trading
      POSTGRES_USER: quantum
      POSTGRES_PASSWORD: quantum123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantum -d quantum_trading"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis - Caching Layer
  redis:
    image: redis:7-alpine
    container_name: quantum-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - quantum-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kafka & Zookeeper - External Message Bus
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: quantum-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - quantum-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: quantum-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Prometheus - Metrics Collection
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: quantum-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - quantum-network

  # Grafana - Metrics Visualization
  grafana:
    image: grafana/grafana:10.0.0
    container_name: quantum-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=quantum123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - quantum-network

  # Quantum Trading API Gateway
  quantum-api-gateway:
    image: openjdk:17-jdk-slim
    container_name: quantum-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AXON_SERVER_HOST=quantum-axon-server
      - DB_HOST=quantum-postgres
      - DB_PORT=5432
      - DB_NAME=quantum_trading
      - DB_USER=quantum
      - DB_PASSWORD=quantum123
      - REDIS_HOST=quantum-redis
      - KAFKA_BROKERS=quantum-kafka:9092
      - KIWOOM_API_URL=http://quantum-kiwoom-api:8100
      - KIS_API_URL=http://quantum-kis-mock-api:8200
    volumes:
      - ../quantum-api/build/libs:/app
      - ./logs/api:/app/logs
    working_dir: /app
    command: java -jar quantum-api-1.0.0.jar
    depends_on:
      - axon-server
      - postgres
      - redis
      - kafka
    networks:
      - quantum-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Quantum Trading Batch Processor
  quantum-batch:
    image: openjdk:17-jdk-slim
    container_name: quantum-batch
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AXON_SERVER_HOST=quantum-axon-server
      - DB_HOST=quantum-postgres
      - DB_PORT=5432
      - DB_NAME=quantum_trading
      - DB_USER=quantum
      - DB_PASSWORD=quantum123
      - REDIS_HOST=quantum-redis
      - KAFKA_BROKERS=quantum-kafka:9092
    volumes:
      - ../quantum-batch/build/libs:/app
      - ./logs/batch:/app/logs
    working_dir: /app
    command: java -jar quantum-batch-1.0.0.jar
    depends_on:
      - axon-server
      - postgres
      - redis
      - kafka
    networks:
      - quantum-network
    restart: unless-stopped

  # ============== MONITORING & MANAGEMENT ==============

  # Kafka UI for monitoring
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: quantum-kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=quantum-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=quantum-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=quantum-zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - quantum-network

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: quantum-redis-commander
    ports:
      - "8091:8081"
    environment:
      - REDIS_HOSTS=local:quantum-redis:6379
    depends_on:
      - redis
    networks:
      - quantum-network

volumes:
  axon-data:
    driver: local
  axon-events:
    driver: local
  axon-config:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  kiwoom-data:
    driver: local

networks:
  quantum-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
