server:
  port: 8080

spring:
  application:
    name: quantum-web-api
  
  # Timezone Configuration
  jackson:
    time-zone: Asia/Seoul

  # H2 In-Memory Database for testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # JPA Configuration for H2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # H2 Console (for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Spring AI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:test-key}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.1

# JWT Configuration
jwt:
  secret: quantum-trading-platform-jwt-secret-key-for-mvp-development-only-change-in-production
  expiration: 86400 # 24 hours in seconds

# Application Configuration
quantum:
  security:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.quantum: DEBUG
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: OFF
    org.springframework.boot.actuator: OFF