# 개발 환경 설정 (local development)
kis:
  api:
    app-key: ${KIS_DEV_APP_KEY:your-dev-app-key}
    app-secret: ${KIS_DEV_APP_SECRET:your-dev-app-secret}
    base-url: ${KIS_BASE_URL:https://openapi.koreainvestment.com:9443}
    account-no: ${KIS_DEV_ACCOUNT_NO:your-dev-account-number}
    environment: sandbox

# 개발 환경에서는 상세 로그
logging:
  level:
    com.quantum: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.batch: DEBUG
    org.quartz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 개발 환경 JPA 설정
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true