spring:
  application:
    name: quantum-trading-app

  # 시크릿 파일 로드
  config:
    import: "classpath:application-secrets.yml"

  # PostgreSQL Database 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/quantum_trading
    driver-class-name: org.postgresql.Driver
    username: quantum
    password: quantum123

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # update 모드로 스키마 자동 생성/수정
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  # H2 Console 설정 (개발용 - 비활성화)
  h2:
    console:
      enabled: false

# KIS API 설정 (시크릿 정보는 application-secrets.yml에서 로드)

kis:
  # 도메인 정보만 여기에 (공개 정보)

  # 도메인 정보 (공개 정보)
  prod: https://openapi.koreainvestment.com:9443
  ops: ws://ops.koreainvestment.com:21000
  vps: https://openapivts.koreainvestment.com:29443
  vops: ws://ops.koreainvestment.com:31000

  # User-Agent (공개 정보)
  my-agent: QuantumTradingApp/1.0

  # 스케줄러 설정
  scheduler:
    enabled: true  # 스케줄러 활성화 여부

# LogTree 설정
logtree:
  enabled: true
  auto-trace-controllers: true
  auto-trace-services: false
  trace-transaction-boundaries: true
  track-errors: true
  exclude-urls:
    - /health
    - /actuator/**
    - /logtree/**
  max-depth: 10
  colored-output: true
  log-style: tree
  admin:
    enabled: true
    max-traces: 100

# 로깅 설정 (상세 설정은 logback-spring.xml에서 관리)
logging:
  config: classpath:logback-spring.xml
  pattern:
    file: logs/
  level:
    root: INFO
    io.github.logtree: DEBUG
    org.hibernate.SQL: DEBUG                    # SQL 쿼리만 표시
    org.hibernate.type.descriptor.sql: WARN     # 파라미터 바인딩 로그 숨김
    org.hibernate.orm.jdbc.bind: WARN           # 파라미터 바인딩 로그 숨김 (Hibernate 6+)
