spring:
  application:
    name: quantum-trading-api

  profiles:
    active: sandbox

  datasource:
    url: jdbc:postgresql://localhost:5432/quantum_trading
    username: quantum
    password: quantum123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Security
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production}
  expiration: 86400000 # 24 hours

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.quantum: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
