global:
  # Slack API URL (환경변수로 설정)
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# 알림 라우팅 설정
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s        # 그룹 형성 대기 시간
  group_interval: 10s    # 그룹 내 추가 알림 간격
  repeat_interval: 12h   # 같은 알림 반복 간격
  receiver: 'quantum-slack'
  
  # 심각도별 라우팅
  routes:
    - match:
        severity: critical
      receiver: 'quantum-slack-critical'
      group_wait: 0s
      repeat_interval: 5m
    
    - match:
        severity: warning  
      receiver: 'quantum-slack-warning'
      repeat_interval: 1h

# 알림 수신자 설정
receivers:
  # 기본 Slack 채널
  - name: 'quantum-slack'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#quantum-alerts'
        title: 'Quantum Trading Platform Alert'
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.job }}
          {{ end }}
        color: 'warning'

  # Critical 알림용 채널
  - name: 'quantum-slack-critical'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#quantum-alerts'
        title: '🚨 CRITICAL: Quantum Trading Platform'
        text: >-
          {{ range .Alerts }}
          *🔥 CRITICAL ALERT 🔥*
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.job }}
          *Duration:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          *Dashboard:* http://localhost:3000
          {{ end }}
        color: 'danger'

  # Warning 알림용 채널  
  - name: 'quantum-slack-warning'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#quantum-alerts'
        title: '⚠️ WARNING: Quantum Trading Platform'
        text: >-
          {{ range .Alerts }}
          *⚠️ Warning Alert*
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.job }}
          {{ end }}
        color: 'warning'

# 알림 억제 규칙 (중복 방지)
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']