apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://quantum-prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://quantum-loki:3100
    uid: loki
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceId=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://quantum-tempo:3200
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
        filters: []
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: 'Tag'
        tag: 'http.status_code'

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://quantum-influxdb:8086
    uid: influxdb
    isDefault: false
    editable: true
    jsonData:
      version: Flux
      organization: quantum-trading
      defaultBucket: realtime-data
      tlsSkipVerify: true
    secureJsonData:
      token: quantum-super-secret-auth-token
