apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://quantum-prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://quantum-loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceId=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://quantum-tempo:3200
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://quantum-influxdb:8086
    uid: influxdb
    isDefault: false
    editable: true
    jsonData:
      version: Flux
      organization: quantum-trading
      defaultBucket: realtime-data
      tlsSkipVerify: true
    secureJsonData:
      token: quantum-super-secret-auth-token
