server:
  port: 8100
  servlet:
    context-path: /

spring:
  application:
    name: kiwoom-api-service

  # Redis 설정 (토큰 캐시용)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Swagger/OpenAPI 설정
  mvc:
    servlet:
      path: /

# Swagger UI 설정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    display-operation-id: true
  show-actuator: true

# 키움증권 API 설정
kiwoom:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ${KIWOOM_APP_KEY:your-app-key-here}
    app-secret: ${KIWOOM_APP_SECRET:your-app-secret-here}
    account-number: ${KIWOOM_ACCOUNT_NUMBER:00000000-00}
    timeout: 30000

# 로깅 설정
logging:
  level:
    root: INFO
    com.quantum.api.kiwoom: DEBUG
    com.quantum.trading.platform.broker.kiwoom: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
