global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files: []

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Actuator 메트릭
  - job_name: 'quantum-web-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s
    scrape_timeout: 10s

  # FastAPI 메트릭 (구현 시)
  - job_name: 'quantum-adapter-kis'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 10s
    scrape_timeout: 10s

  # Node Exporter (시스템 메트릭, 선택사항)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # PostgreSQL 메트릭 (구현 시)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['host.docker.internal:9187']