server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot API 실시간 로그 파일 수집
  - job_name: quantum-web-api-realtime
    static_configs:
      - targets:
          - localhost
        labels:
          job: quantum-web-api
          service: quantum-web-api
          environment: development
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            service: service
      - labels:
          level:
          service: