server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot API 로그 파일 수집
  - job_name: quantum-web-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: quantum-web-api
          service: quantum-web-api
          environment: development
          __path__: /app/logs/quantum-web-api.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger_name
            timestamp: "\"@timestamp\""
            message: message
            service: service
            trace_id: traceId
            span_id: spanId
      - labels:
          level:
          logger:
          service:
          trace_id:
          span_id:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.999999999Z"

  # 향후 다른 서비스 로그 추가 가능
  - job_name: quantum-adapter-kis
    static_configs:
      - targets:
          - localhost
        labels:
          job: quantum-adapter-kis
          service: quantum-adapter-kis
          environment: development
          __path__: /app/logs/quantum-adapter-kis*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            service: service
            timestamp: timestamp
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.999999999Z"

  - job_name: quantum-web-client
    static_configs:
      - targets:
          - localhost
        labels:
          job: quantum-web-client
          service: quantum-web-client
          environment: development
          __path__: /app/logs/quantum-web-client*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            service: service
            timestamp: timestamp
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05"