# 리스크 관리 설정

# 포트폴리오 레벨 리스크 관리
portfolio_risk:
  # 손실 제한
  max_daily_loss: -3.0          # 일일 최대 손실률 -3%
  max_weekly_loss: -8.0         # 주간 최대 손실률 -8%
  max_monthly_loss: -15.0       # 월간 최대 손실률 -15%
  
  # 집중도 리스크
  max_sector_concentration: 25.0   # 단일섹터 최대 25%
  max_stock_concentration: 20.0    # 단일종목 최대 20%
  max_correlation_threshold: 0.7   # 종목간 상관계수 0.7 이하
  
  # 유동성 리스크  
  min_daily_volume: 1000000000    # 최소 일거래대금 10억원
  max_position_vs_adv: 5.0        # 포지션 / 평균일거래량 5% 이하

# 섹터별 리스크 관리
sector_risk:
  조선:
    stop_loss: -10.0            # 조선업 변동성 고려 -10%
    profit_target: 20.0         # 목표 수익률 20%
    max_holding_period: 120     # 최대 보유 120일 (업황 사이클)
    volatility_limit: 35.0      # 변동성 35% 이하
    
  방산:
    stop_loss: -8.0             # 정부 정책 리스크 고려
    profit_target: 18.0
    max_holding_period: 90      # 정책 변화 고려 90일
    volatility_limit: 30.0
    
  원자력:
    stop_loss: -9.0             # 정책/인허가 리스크
    profit_target: 25.0         # 신규 사업 높은 수익 기대
    max_holding_period: 150     # 장기 프로젝트 150일
    volatility_limit: 40.0
    
  AI:
    stop_loss: -12.0            # 기술주 높은 변동성
    profit_target: 30.0         # 고성장 기대
    max_holding_period: 60      # 빠른 기술 변화 60일
    volatility_limit: 45.0
    
  반도체:
    stop_loss: -10.0            # 사이클 변동성
    profit_target: 25.0
    max_holding_period: 90      # 메모리 사이클 90일
    volatility_limit: 35.0
    
  바이오:
    stop_loss: -15.0            # 신약 개발 불확실성
    profit_target: 35.0         # 높은 수익 잠재력
    max_holding_period: 180     # 장기 개발 주기 180일
    volatility_limit: 50.0

# 종목별 리스크 관리
stock_specific_risk:
  # 대형주 (시가총액 10조 이상)
  large_cap:
    max_position_size: 2000000   # 최대 포지션 200만원
    stop_loss: -8.0
    volatility_limit: 30.0
    
  # 중형주 (시가총액 1-10조)  
  mid_cap:
    max_position_size: 1500000   # 최대 포지션 150만원
    stop_loss: -10.0
    volatility_limit: 35.0
    
  # 소형주 (시가총액 1조 미만)
  small_cap:
    max_position_size: 1000000   # 최대 포지션 100만원
    stop_loss: -12.0
    volatility_limit: 45.0

# 시장 환경별 리스크 조정
market_environment:
  bull_market:
    risk_multiplier: 1.2        # 강세장 리스크 20% 증가
    stop_loss_relax: 2.0        # 손절선 2%p 완화
    
  bear_market:
    risk_multiplier: 0.7        # 약세장 리스크 30% 감소  
    stop_loss_tighten: -3.0     # 손절선 3%p 강화
    cash_increase: 30.0         # 현금 비중 30% 증가
    
  sideways_market:
    risk_multiplier: 1.0        # 횡보장 기본 리스크
    rebalancing_frequency: 14   # 2주마다 리밸런싱

# 긴급 상황 대응
emergency_controls:
  # 자동 전량 매도 조건
  panic_sell_triggers:
    portfolio_loss: -20.0       # 포트폴리오 -20% 손실
    market_crash: -10.0         # 시장 일일 -10% 하락
    volatility_spike: 100.0     # 변동성 100% 초과
    
  # 매매 중단 조건
  trading_halt_triggers:
    consecutive_losses: 5       # 연속 5회 손실거래
    daily_loss_limit: -5.0      # 일일 -5% 손실
    
  # 복구 조건
  resume_conditions:
    cooling_period: 24          # 24시간 대기
    market_stability: 3         # 3일 연속 안정
    manual_approval: true       # 수동 승인 필요

# 리스크 모니터링
risk_monitoring:
  real_time_alerts:
    enabled: true
    alert_channels: ["console", "log"]
    
  risk_metrics:
    - "portfolio_var"           # 포트폴리오 VaR
    - "sector_concentration"    # 섹터 집중도
    - "correlation_matrix"      # 상관관계 매트릭스
    - "drawdown"               # 최대 손실폭
    - "sharpe_ratio"           # 샤프 비율
    
  reporting_frequency: "daily"  # 일일 리스크 리포트