# 섹터별 분산투자 전략 설정

# 매매 전략 설정
trading_strategy:
  mode: "manual"  # manual: 수동승인, auto: 자동실행
  execution_type: "market"  # market: 시장가, limit: 지정가
  
  # 매수 신호 조건
  buy_signals:
    technical_indicators:
      golden_cross: true        # 골든크로스 신호
      rsi_oversold: 30         # RSI 30 이하 과매도
      volume_surge: 1.5        # 거래량 평균 대비 1.5배 이상
    
    sector_momentum:
      min_sector_performance: -5.0  # 섹터 최근 성과 -5% 이상
      news_sentiment: "positive"     # 긍정적 뉴스 확인
    
    market_conditions:
      market_trend: "neutral"   # neutral 이상일 때만 매수
      volatility_max: 30.0      # 변동성 30% 이하일 때만

  # 매도 신호 조건  
  sell_signals:
    profit_taking:
      target_profit: 15.0       # 목표 수익률 15%
      trailing_stop: 5.0        # 고점대비 -5% 추적손절
    
    risk_management:
      stop_loss: -8.0           # 손절매 -8%
      max_holding_days: 90      # 최대 보유일 90일
      
    technical_exit:
      death_cross: true         # 데드크로스 신호
      rsi_overbought: 70        # RSI 70 이상 과매수

# 포지션 관리
position_management:
  initial_investment: 10000000   # 초기 투자금액 1천만원
  sector_allocation: "equal"     # 섹터별 균등 배분
  max_positions: 12             # 최대 보유종목 12개 (섹터당 2개)
  
  cash_reserve: 10.0            # 현금 비중 10% 유지
  rebalancing_threshold: 5.0     # 목표 비중과 5% 차이시 리밸런싱

# 실행 설정
execution_settings:
  market_hours_only: true       # 장중에만 매매
  price_limit_range: 3.0        # 현재가 대비 ±3% 내 지정가
  
  confirmation_required: true    # 매매 전 사용자 승인 필요
  max_daily_trades: 6           # 하루 최대 거래 6회
  
  order_amount_min: 100000      # 최소 주문금액 10만원
  order_amount_max: 2000000     # 최대 주문금액 200만원

# 모니터링 설정
monitoring:
  update_interval: 300          # 5분마다 시세 업데이트
  alert_conditions:
    profit_threshold: 10.0      # 수익률 10% 달성시 알림
    loss_threshold: -5.0        # 손실률 -5% 도달시 알림
    
  performance_tracking:
    benchmark: "KOSPI200"       # 벤치마크 지수
    tracking_period: 30         # 성과 추적 기간 30일
    
# 로깅 설정
logging:
  level: "detailed"             # 상세 로깅
  save_trades: true            # 매매 기록 저장
  save_analysis: true          # 분석 결과 저장
  
  log_retention_days: 365      # 로그 보관 기간 1년
  export_format: ["csv", "json"]  # 내보내기 형식