# Prometheus Configuration for Quantum Trading Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# AlertManager 연동 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - quantum-alertmanager:9093

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Axon Server metrics
  - job_name: 'axon-server'
    static_configs:
      - targets: ['quantum-axon-server:8024']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Quantum Web API metrics
  - job_name: 'quantum-web-api'
    static_configs:
      - targets: ['quantum-web-api:10101']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Kiwoom Adapter metrics
  - job_name: 'quantum-kiwoom-adapter'
    static_configs:
      - targets: ['quantum-kiwoom-adapter:10201']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['quantum-loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Promtail metrics
  - job_name: 'promtail'
    static_configs:
      - targets: ['quantum-promtail:9080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['quantum-tempo:3200']
    metrics_path: '/metrics'
    scrape_interval: 30s
