# Prometheus Configuration for Quantum Trading Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'quantum-trading'
    environment: 'production'

# AlertManager 연동 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ============== APPLICATION SERVICES ==============
  
  # Axon Server metrics
  - job_name: 'axon-server'
    static_configs:
      - targets: ['quantum-axon-server:8024']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Quantum Web API metrics
  - job_name: 'quantum-web-api'
    static_configs:
      - targets: ['quantum-web-api:10101']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Kiwoom Adapter metrics
  - job_name: 'quantum-kiwoom-adapter'
    static_configs:
      - targets: ['quantum-kiwoom-adapter:10201']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # ============== INFRASTRUCTURE SERVICES ==============

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['quantum-postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['quantum-redis-exporter:9121']
    scrape_interval: 30s

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['quantum-kafka-exporter:9308']
    scrape_interval: 30s

  # InfluxDB metrics
  - job_name: 'influxdb'
    static_configs:
      - targets: ['quantum-influxdb:8086']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # ============== MONITORING SERVICES ==============

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['quantum-loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Promtail metrics
  - job_name: 'promtail'
    static_configs:
      - targets: ['quantum-promtail:9080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['quantum-tempo:3200']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['quantum-grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # AlertManager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['quantum-alertmanager:9093']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # ============== CONTAINER METRICS ==============

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['quantum-cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
